services:
  db:
    image: postgres:14
    container_name: notes-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notes_app
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5433"

  backend:
    build:
      context: ./backend
    container_name: notes-backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: notes_app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: notes-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db-data:
